// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adresses.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAddress = `-- name: GetAddress :one
SELECT id, user_id, location, created_at, updated_at FROM addresses
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetAddress(ctx context.Context, userID uuid.UUID) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddress, userID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAddress = `-- name: UpsertAddress :one
INSERT INTO addresses (user_id, location)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET location   = EXCLUDED.location,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, location, created_at, updated_at
`

type UpsertAddressParams struct {
	UserID   uuid.UUID
	Location sql.NullString
}

func (q *Queries) UpsertAddress(ctx context.Context, arg UpsertAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, upsertAddress, arg.UserID, arg.Location)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
