// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createKey = `-- name: CreateKey :one
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, key_hash, key_prefix, last_used_at, revoked_at, created_at
`

type CreateKeyParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	KeyHash   string
	KeyPrefix string
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findLiveKeyByHash = `-- name: FindLiveKeyByHash :one
SELECT
    api_keys.id,
    api_keys.user_id,
    users.username,
    users.role
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.key_hash = $1
    AND api_keys.revoked_at IS NULL
    AND users.deleted_at IS NULL
`

type FindLiveKeyByHashRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Username string
	Role     string
}

func (q *Queries) FindLiveKeyByHash(ctx context.Context, keyHash string) (FindLiveKeyByHashRow, error) {
	row := q.db.QueryRowContext(ctx, findLiveKeyByHash, keyHash)
	var i FindLiveKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const listKeysForUser = `-- name: ListKeysForUser :many
SELECT id, user_id, name, key_prefix, last_used_at, revoked_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListKeysForUserRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
	CreatedAt  time.Time
}

func (q *Queries) ListKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListKeysForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeysForUserRow
	for rows.Next() {
		var i ListKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeKey = `-- name: RevokeKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1
    AND user_id = $2
    AND revoked_at IS NULL
`

type RevokeKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeKey(ctx context.Context, arg RevokeKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeKeysForUser = `-- name: RevokeKeysForUser :exec
UPDATE api_keys
SET revoked_at = now()
WHERE user_id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeKeysForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeKeysForUser, userID)
	return err
}

const touchKey = `-- name: TouchKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchKey, id)
	return err
}
