// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, key_hash, key_prefix, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID
	Name      string
	KeyHash   string
	KeyPrefix string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findLiveKeyByHash = `-- name: FindLiveKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, last_used_at, revoked_at, created_at FROM api_keys
WHERE key_hash = $1
    AND revoked_at IS NULL
`

// Revoked keys are filtered here rather than in Go, so a second caller cannot
// forget the rule.
func (q *Queries) FindLiveKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, findLiveKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, user_id, name, key_prefix, last_used_at, revoked_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysForUserRow struct {
	ID         int32
	UserID     uuid.UUID
	Name       string
	KeyPrefix  string
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
	CreatedAt  time.Time
}

// Columns named deliberately: a SELECT * would put key_hash in the generated
// struct, one careless DTO change away from a response body.
func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysForUserRow
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1
    AND user_id = $2
    AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     int32
	UserID uuid.UUID
}

// Scoped to the owner: without the user_id clause, DELETE /me/api-keys/1 would
// switch off a stranger's integration.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

// By id, not by hash: the key has already been looked up by the time this
// runs, so there is no reason to hash and search again.
func (q *Queries) TouchAPIKey(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, id)
	return err
}
