// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const blockExistsBetween = `-- name: BlockExistsBetween :one
SELECT EXISTS (
    SELECT 1
        FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
        OR (blocker_id = $2 AND blocked_id = $1)
)
`

type BlockExistsBetweenParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) BlockExistsBetween(ctx context.Context, arg BlockExistsBetweenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, blockExistsBetween, arg.UserA, arg.UserB)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const listBlocks = `-- name: ListBlocks :many
SELECT
    users.id,
    users.username,
    blocks.created_at
FROM blocks
JOIN users ON users.id = blocks.blocked_id
WHERE blocks.blocker_id = $1
ORDER BY users.username
`

type ListBlocksRow struct {
	ID        uuid.UUID
	Username  string
	CreatedAt sql.NullTime
}

func (q *Queries) ListBlocks(ctx context.Context, blockerID uuid.UUID) ([]ListBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlocks, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlocksRow
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
