// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package database

import (
	"context"
	"database/sql"
)

const listCategories = `-- name: ListCategories :many
SELECT slug, name, parent_slug FROM categories
ORDER BY COALESCE(parent_slug, slug), parent_slug NULLS FIRST, slug
`

type ListCategoriesRow struct {
	Slug       string
	Name       string
	ParentSlug sql.NullString
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.ParentSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
