// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, listing_id, listing_title, buyer_id, seller_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, listing_id, listing_title, buyer_id, seller_id, status, created_at, updated_at
`

type CreateConversationParams struct {
	ID           uuid.UUID
	ListingID    uuid.NullUUID
	ListingTitle string
	BuyerID      uuid.UUID
	SellerID     uuid.UUID
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.ListingID,
		arg.ListingTitle,
		arg.BuyerID,
		arg.SellerID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ListingTitle,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, listing_id, listing_title, buyer_id, seller_id, status, created_at, updated_at FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ListingTitle,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, listing_id, listing_title, buyer_id, seller_id, status, created_at, updated_at FROM conversations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetConversationForUpdate(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationForUpdate, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ListingTitle,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
    c.id, c.listing_id, c.listing_title, c.buyer_id, c.seller_id, c.status, c.created_at, c.updated_at,
    u.id                    AS other_user_id,
    u.username              AS other_username,
    u.deleted_at            AS other_deleted_at,
    u.last_seen_at          AS other_last_seen_at,
    -- A block in EITHER direction hides presence. The blocker never sees the
    -- thread at all (see the WHERE below), so the direction that matters here
    -- is the blocked party still watching the blocker go online.
    COALESCE(u.show_online_status AND NOT EXISTS (
        SELECT 1 FROM blocks b
        WHERE (b.blocker_id = $1 AND b.blocked_id = u.id)
           OR (b.blocker_id = u.id AND b.blocked_id = $1)
    ), false)::boolean AS other_show_online_status,
    COALESCE(lm.body, '')   AS last_message_body,
    lm.created_at           AS last_message_at,
    (SELECT COUNT(*)
          FROM messages m
        WHERE m.conversation_id = c.id
          AND m.sender_id <> $1
          AND m.read_at IS NULL) AS unread_count
FROM conversations c
JOIN users u ON u.id = CASE WHEN c.buyer_id = $1
                            THEN c.seller_id
                            ELSE c.buyer_id END
LEFT JOIN LATERAL (
    SELECT body, created_at
      FROM messages
     WHERE conversation_id = c.id
     ORDER BY id DESC
     LIMIT 1
) lm ON TRUE
WHERE (c.buyer_id = $1 OR c.seller_id = $1)
  AND NOT EXISTS (
      SELECT 1
        FROM blocks
        WHERE blocks.blocker_id = $1
          AND blocks.blocked_id = u.id
  )
`

type ListConversationsForUserRow struct {
	ID                    uuid.UUID
	ListingID             uuid.NullUUID
	ListingTitle          string
	BuyerID               uuid.UUID
	SellerID              uuid.UUID
	Status                string
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	OtherUserID           uuid.UUID
	OtherUsername         string
	OtherDeletedAt        sql.NullTime
	OtherLastSeenAt       sql.NullTime
	OtherShowOnlineStatus bool
	LastMessageBody       string
	LastMessageAt         sql.NullTime
	UnreadCount           int64
}

func (q *Queries) ListConversationsForUser(ctx context.Context, userID uuid.UUID) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.ListingTitle,
			&i.BuyerID,
			&i.SellerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.OtherDeletedAt,
			&i.OtherLastSeenAt,
			&i.OtherShowOnlineStatus,
			&i.LastMessageBody,
			&i.LastMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchConversation, id)
	return err
}

const updateConversationStatus = `-- name: UpdateConversationStatus :one
UPDATE conversations
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, listing_id, listing_title, buyer_id, seller_id, status, created_at, updated_at
`

type UpdateConversationStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversationStatus, arg.ID, arg.Status)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ListingTitle,
		&i.BuyerID,
		&i.SellerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
