// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteFollowsForUser = `-- name: DeleteFollowsForUser :exec
DELETE FROM follows WHERE follower_id = $1 OR followee_id = $1
`

func (q *Queries) DeleteFollowsForUser(ctx context.Context, followerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsForUser, followerID)
	return err
}

const followUser = `-- name: FollowUser :execrows
INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, followee_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listFollowers = `-- name: ListFollowers :many
SELECT
    users.id,
    users.username,
    users.last_seen_at,
    profiles.avatar_filename,
    -- Plain, because the WHERE below now drops a blocked person from the list
    -- outright: hiding their presence was the older, narrower rule.
    users.show_online_status
FROM follows
JOIN users ON users.id = follows.follower_id
LEFT JOIN profiles ON profiles.id = users.id
WHERE follows.followee_id = $1
  AND users.is_visible
  -- Symmetric, and it removes the row rather than dimming it: a block hides
  -- the two of you from each other everywhere else, and a name left in a list
  -- you cannot open is the inconsistency.
  AND NOT EXISTS (
      SELECT 1 FROM blocks b
      WHERE (b.blocker_id = $2 AND b.blocked_id = users.id)
         OR (b.blocker_id = users.id AND b.blocked_id = $2)
  )
ORDER BY users.username
`

type ListFollowersParams struct {
	SubjectID uuid.UUID
	ViewerID  uuid.UUID
}

type ListFollowersRow struct {
	ID               uuid.UUID
	Username         string
	LastSeenAt       sql.NullTime
	AvatarFilename   sql.NullString
	ShowOnlineStatus bool
}

// LEFT: an inner join would silently drop anyone without a profile row.
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.SubjectID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.LastSeenAt,
			&i.AvatarFilename,
			&i.ShowOnlineStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
    users.id,
    users.username,
    users.last_seen_at,
    profiles.avatar_filename,
    -- Plain, because the WHERE below now drops a blocked person from the list
    -- outright: hiding their presence was the older, narrower rule.
    users.show_online_status
FROM follows
JOIN users ON users.id = follows.followee_id
LEFT JOIN profiles ON profiles.id = users.id
WHERE follows.follower_id = $1
  AND users.is_visible
  -- Symmetric, and it removes the row rather than dimming it: a block hides
  -- the two of you from each other everywhere else, and a name left in a list
  -- you cannot open is the inconsistency.
  AND NOT EXISTS (
      SELECT 1 FROM blocks b
      WHERE (b.blocker_id = $2 AND b.blocked_id = users.id)
         OR (b.blocker_id = users.id AND b.blocked_id = $2)
  )
ORDER BY users.username
`

type ListFollowingParams struct {
	SubjectID uuid.UUID
	ViewerID  uuid.UUID
}

type ListFollowingRow struct {
	ID               uuid.UUID
	Username         string
	LastSeenAt       sql.NullTime
	AvatarFilename   sql.NullString
	ShowOnlineStatus bool
}

// LEFT: an inner join would silently drop anyone without a profile row.
func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.SubjectID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.LastSeenAt,
			&i.AvatarFilename,
			&i.ShowOnlineStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :execrows
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
