// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_images.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countListingImages = `-- name: CountListingImages :one
SELECT COUNT(*) FROM listing_images
WHERE listing_id = $1
`

func (q *Queries) CountListingImages(ctx context.Context, listingID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListingImages, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListingImage = `-- name: CreateListingImage :one
INSERT INTO listing_images (id, listing_id, filename, position)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT MAX(position) + 1 FROM listing_images WHERE listing_id = $2), 0)
)
RETURNING id, listing_id, filename, position, created_at
`

type CreateListingImageParams struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	Filename  string
}

func (q *Queries) CreateListingImage(ctx context.Context, arg CreateListingImageParams) (ListingImage, error) {
	row := q.db.QueryRowContext(ctx, createListingImage, arg.ID, arg.ListingID, arg.Filename)
	var i ListingImage
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.Filename,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImagesForListing = `-- name: DeleteImagesForListing :many
DELETE FROM listing_images
WHERE listing_id = $1
RETURNING filename
`

func (q *Queries) DeleteImagesForListing(ctx context.Context, listingID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteImagesForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteListingImage = `-- name: DeleteListingImage :one
DELETE FROM listing_images
WHERE id = $1 AND listing_id = $2
RETURNING filename
`

type DeleteListingImageParams struct {
	ID        uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) DeleteListingImage(ctx context.Context, arg DeleteListingImageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteListingImage, arg.ID, arg.ListingID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const listImagesForListings = `-- name: ListImagesForListings :many
SELECT id, listing_id, filename, position, created_at FROM listing_images
WHERE listing_id = ANY($1::uuid[])
ORDER BY listing_id, position, id
`

func (q *Queries) ListImagesForListings(ctx context.Context, listingIds []uuid.UUID) ([]ListingImage, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForListings, pq.Array(listingIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingImage
	for rows.Next() {
		var i ListingImage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Filename,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingImages = `-- name: ListListingImages :many
SELECT id, listing_id, filename, position, created_at FROM listing_images
WHERE listing_id = $1
ORDER BY position, id
`

func (q *Queries) ListListingImages(ctx context.Context, listingID uuid.UUID) ([]ListingImage, error) {
	rows, err := q.db.QueryContext(ctx, listListingImages, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingImage
	for rows.Next() {
		var i ListingImage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Filename,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListingImagePositions = `-- name: SetListingImagePositions :execrows
UPDATE listing_images AS li
SET position = v.ord - 1
FROM unnest($2::uuid[]) WITH ORDINALITY AS v(id, ord)
WHERE li.id = v.id AND li.listing_id = $1
`

type SetListingImagePositionsParams struct {
	ListingID uuid.UUID
	ImageIds  []uuid.UUID
}

// One statement for the whole gallery. WITH ORDINALITY numbers the array as it
// arrives, so the caller sends the ids in the wanted order and the positions
// are derived here rather than passed alongside - two parallel arrays could
// disagree, one cannot.
//
// The listing_id in the WHERE is what stops an id from another listing being
// renumbered; :execrows is how the caller checks every id it sent matched a row.
func (q *Queries) SetListingImagePositions(ctx context.Context, arg SetListingImagePositionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setListingImagePositions, arg.ListingID, pq.Array(arg.ImageIds))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
