// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_images.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const countListingImages = `-- name: CountListingImages :one
SELECT COUNT(*) FROM listing_images
WHERE listing_id = $1
`

func (q *Queries) CountListingImages(ctx context.Context, listingID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListingImages, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListingImage = `-- name: CreateListingImage :one
INSERT INTO listing_images (listing_id, filename, position)
VALUES (
    $1,
    $2,
    COALESCE((SELECT MAX(position) + 1 FROM listing_images WHERE listing_id = $1), 0)
)
RETURNING id, listing_id, filename, position, created_at
`

type CreateListingImageParams struct {
	ListingID int32
	Filename  string
}

func (q *Queries) CreateListingImage(ctx context.Context, arg CreateListingImageParams) (ListingImage, error) {
	row := q.db.QueryRowContext(ctx, createListingImage, arg.ListingID, arg.Filename)
	var i ListingImage
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.Filename,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImagesForListing = `-- name: DeleteImagesForListing :many
DELETE FROM listing_images
WHERE listing_id = $1
RETURNING filename
`

func (q *Queries) DeleteImagesForListing(ctx context.Context, listingID int32) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteImagesForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var filename string
		if err := rows.Scan(&filename); err != nil {
			return nil, err
		}
		items = append(items, filename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteListingImage = `-- name: DeleteListingImage :one
DELETE FROM listing_images
WHERE id = $1 AND listing_id = $2
RETURNING filename
`

type DeleteListingImageParams struct {
	ID        int32
	ListingID int32
}

func (q *Queries) DeleteListingImage(ctx context.Context, arg DeleteListingImageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteListingImage, arg.ID, arg.ListingID)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const listImagesForListings = `-- name: ListImagesForListings :many
SELECT id, listing_id, filename, position, created_at FROM listing_images
WHERE listing_id = ANY($1::int[])
ORDER BY listing_id, position, id
`

func (q *Queries) ListImagesForListings(ctx context.Context, listingIds []int32) ([]ListingImage, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForListings, pq.Array(listingIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingImage
	for rows.Next() {
		var i ListingImage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Filename,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingImages = `-- name: ListListingImages :many
SELECT id, listing_id, filename, position, created_at FROM listing_images
WHERE listing_id = $1
ORDER BY position, id
`

func (q *Queries) ListListingImages(ctx context.Context, listingID int32) ([]ListingImage, error) {
	rows, err := q.db.QueryContext(ctx, listListingImages, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingImage
	for rows.Next() {
		var i ListingImage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Filename,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
