// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createListing = `-- name: CreateListing :one
INSERT INTO listings (id, seller_id, title, description, category, price, quantity, unit)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

type CreateListingParams struct {
	ID          uuid.UUID
	SellerID    uuid.UUID
	Title       string
	Description sql.NullString
	Category    string
	Price       string
	Quantity    int32
	Unit        string
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRowContext(ctx, createListing,
		arg.ID,
		arg.SellerID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Price,
		arg.Quantity,
		arg.Unit,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const decrementListingQuantity = `-- name: DecrementListingQuantity :one
UPDATE listings
SET quantity = quantity - $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND quantity >= $2
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

type DecrementListingQuantityParams struct {
	ID       uuid.UUID
	Quantity int32
}

func (q *Queries) DecrementListingQuantity(ctx context.Context, arg DecrementListingQuantityParams) (Listing, error) {
	row := q.db.QueryRowContext(ctx, decrementListingQuantity, arg.ID, arg.Quantity)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const deleteListing = `-- name: DeleteListing :exec
DELETE FROM listings
WHERE id = $1
`

func (q *Queries) DeleteListing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteListing, id)
	return err
}

const getListing = `-- name: GetListing :one
SELECT id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at FROM listings
WHERE id = $1
`

func (q *Queries) GetListing(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRowContext(ctx, getListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const getListingForUpdate = `-- name: GetListingForUpdate :one
SELECT id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at FROM listings
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetListingForUpdate(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRowContext(ctx, getListingForUpdate, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const incrementListingQuantity = `-- name: IncrementListingQuantity :one
UPDATE listings
SET quantity = quantity + $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

type IncrementListingQuantityParams struct {
	ID       uuid.UUID
	Quantity int32
}

func (q *Queries) IncrementListingQuantity(ctx context.Context, arg IncrementListingQuantityParams) (Listing, error) {
	row := q.db.QueryRowContext(ctx, incrementListingQuantity, arg.ID, arg.Quantity)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listListings = `-- name: ListListings :many
SELECT id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at FROM listings
WHERE quantity > 0 AND removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListListings(ctx context.Context) ([]Listing, error) {
	rows, err := q.db.QueryContext(ctx, listListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings
SET title = $2,
    description = $3,
    category = $4,
    price = $5,
    quantity = $6,
    unit = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

type UpdateListingParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Category    string
	Price       string
	Quantity    int32
	Unit        string
}

func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRowContext(ctx, updateListing,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Price,
		arg.Quantity,
		arg.Unit,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}
