// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing_reports.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO listing_reports (id, listing_id, reporter_id, reason, detail)
VALUES ($1, $2, $3, $4, $5)
`

type CreateReportParams struct {
	ID         uuid.UUID
	ListingID  uuid.UUID
	ReporterID uuid.NullUUID
	Reason     string
	Detail     sql.NullString
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.ID,
		arg.ListingID,
		arg.ReporterID,
		arg.Reason,
		arg.Detail,
	)
	return err
}
