// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadForUser = `-- name: CountUnreadForUser :one
SELECT COUNT(*) FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE (c.buyer_id = $1 OR c.seller_id = $1)
  AND m.sender_id <> $1
  AND m.read_at IS NULL
`

func (q *Queries) CountUnreadForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, body, read_at, created_at
`

type CreateMessageParams struct {
	ConversationID int32
	SenderID       uuid.UUID
	Body           string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, conversation_id, sender_id, body, read_at, created_at FROM messages
WHERE conversation_id = $1
  AND id > $2
ORDER BY id
LIMIT $3
`

type ListMessagesAfterParams struct {
	ConversationID int32
	AfterID        int32
	MaxRows        int32
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAfter, arg.ConversationID, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, sender_id, body, read_at, created_at FROM messages
WHERE conversation_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	ConversationID int32
	Limit          int32
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :execrows
UPDATE messages
SET read_at = CURRENT_TIMESTAMP
WHERE conversation_id = $1
  AND sender_id <> $2
  AND read_at IS NULL
`

type MarkMessagesReadParams struct {
	ConversationID int32
	ReaderID       uuid.UUID
}

func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessagesRead, arg.ConversationID, arg.ReaderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
