// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createModerationAction = `-- name: CreateModerationAction :one
INSERT INTO moderation_actions (id, listing_id, moderator_id, action, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, listing_id, moderator_id, action, note, created_at
`

type CreateModerationActionParams struct {
	ID          uuid.UUID
	ListingID   uuid.UUID
	ModeratorID uuid.NullUUID
	Action      string
	Note        sql.NullString
}

func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRowContext(ctx, createModerationAction,
		arg.ID,
		arg.ListingID,
		arg.ModeratorID,
		arg.Action,
		arg.Note,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ModeratorID,
		&i.Action,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listModerationActions = `-- name: ListModerationActions :many
SELECT id, listing_id, moderator_id, action, note, created_at
FROM moderation_actions
WHERE listing_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListModerationActions(ctx context.Context, listingID uuid.UUID) ([]ModerationAction, error) {
	rows, err := q.db.QueryContext(ctx, listModerationActions, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationAction
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.ModeratorID,
			&i.Action,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportedListings = `-- name: ListReportedListings :many
SELECT
    l.id AS listing_id,
    l.title,
    l.seller_id,
    l.removed_at,
    count(*) AS report_count,
    min(r.created_at)::timestamptz AS first_reported_at
FROM listing_reports r
JOIN listings l ON l.id = r.listing_id
WHERE r.status = 'open'
GROUP BY l.id, l.title, l.seller_id, l.removed_at
ORDER BY min(r.created_at)
`

type ListReportedListingsRow struct {
	ListingID       uuid.UUID
	Title           string
	SellerID        uuid.UUID
	RemovedAt       sql.NullTime
	ReportCount     int64
	FirstReportedAt time.Time
}

func (q *Queries) ListReportedListings(ctx context.Context) ([]ListReportedListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportedListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportedListingsRow
	for rows.Next() {
		var i ListReportedListingsRow
		if err := rows.Scan(
			&i.ListingID,
			&i.Title,
			&i.SellerID,
			&i.RemovedAt,
			&i.ReportCount,
			&i.FirstReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsForListing = `-- name: ListReportsForListing :many
SELECT id, reporter_id, reason, detail, status, created_at
FROM listing_reports
WHERE listing_id = $1
ORDER BY created_at DESC
`

type ListReportsForListingRow struct {
	ID         uuid.UUID
	ReporterID uuid.NullUUID
	Reason     string
	Detail     sql.NullString
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) ListReportsForListing(ctx context.Context, listingID uuid.UUID) ([]ListReportsForListingRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportsForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsForListingRow
	for rows.Next() {
		var i ListReportsForListingRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.Reason,
			&i.Detail,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpenReports = `-- name: ResolveOpenReports :execrows
UPDATE listing_reports
SET status = $2
WHERE listing_id = $1 AND status = 'open'
`

type ResolveOpenReportsParams struct {
	ListingID uuid.UUID
	Status    string
}

func (q *Queries) ResolveOpenReports(ctx context.Context, arg ResolveOpenReportsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveOpenReports, arg.ListingID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreListing = `-- name: RestoreListing :one
UPDATE listings
SET removed_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

func (q *Queries) RestoreListing(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRowContext(ctx, restoreListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const setListingRemoved = `-- name: SetListingRemoved :one
UPDATE listings
SET removed_at = now(),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, seller_id, title, description, category, price, quantity, unit, created_at, updated_at, removed_at
`

func (q *Queries) SetListingRemoved(ctx context.Context, id uuid.UUID) (Listing, error) {
	row := q.db.QueryRowContext(ctx, setListingRemoved, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}
