// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Listing struct {
	ID          int32
	SellerID    int32
	Title       string
	Description sql.NullString
	Category    string
	Price       string
	Quantity    int32
	Unit        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Profile struct {
	ID          int64
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

type User struct {
	ID        int32
	Email     string
	Firstname string
	Lastname  string
	Password  string
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
