// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Address struct {
	ID        int32
	UserID    int32
	Location  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Listing struct {
	ID          int32
	SellerID    uuid.UUID
	Title       string
	Description sql.NullString
	Category    string
	Price       string
	Quantity    int32
	Unit        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Profile struct {
	ID          uuid.UUID
	Firstname   string
	Lastname    string
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Password  string
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
