// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (
    id, user_id, kind, listing_title, order_id, conversation_id, actor_id, listing_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateNotificationParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Kind           string
	ListingTitle   sql.NullString
	OrderID        uuid.NullUUID
	ConversationID uuid.NullUUID
	ActorID        uuid.NullUUID
	ListingID      uuid.NullUUID
}

// Exactly one of the four subject columns is set, enforced by
// notifications_one_subject_check: a row the UI cannot route is not worth
// writing. listing_title is a snapshot where a listing is involved and null
// where none is - a follow has no listing to name.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.ListingTitle,
		arg.OrderID,
		arg.ConversationID,
		arg.ActorID,
		arg.ListingID,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, listing_title, order_id, conversation_id, read_at, created_at, actor_id, listing_id FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	UserID uuid.UUID
	Limit  int32
}

// id breaks the tie: created_at defaults to now(), and two rows written in one
// transaction share it. Ids are time-ordered, so this stays chronological.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ListingTitle,
			&i.OrderID,
			&i.ConversationID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ActorID,
			&i.ListingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications
SET read_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
