// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findUserByProviderIdentity = `-- name: FindUserByProviderIdentity :one
SELECT users.id, users.email, users.username, users.password, users.role, users.created_at, users.updated_at, users.last_seen_at, users.show_online_status
FROM oauth_identities
JOIN users ON users.id = oauth_identities.user_id
WHERE oauth_identities.provider = $1
    AND oauth_identities.provider_user_id = $2
`

type FindUserByProviderIdentityParams struct {
	Provider       string
	ProviderUserID string
}

type FindUserByProviderIdentityRow struct {
	User User
}

// Joined rather than a second lookup: the callback needs the user, and this way
// the role and username come back fresh rather than cached in the link.
func (q *Queries) FindUserByProviderIdentity(ctx context.Context, arg FindUserByProviderIdentityParams) (FindUserByProviderIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i FindUserByProviderIdentityRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.Username,
		&i.User.Password,
		&i.User.Role,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.LastSeenAt,
		&i.User.ShowOnlineStatus,
	)
	return i, err
}

const linkIdentity = `-- name: LinkIdentity :exec
INSERT INTO oauth_identities (provider, provider_user_id, user_id)
VALUES ($1, $2, $3)
`

type LinkIdentityParams struct {
	Provider       string
	ProviderUserID string
	UserID         uuid.UUID
}

// No ON CONFLICT: a duplicate means two callbacks are racing to claim the same
// provider account, and the 23505 is the right answer rather than something to
// swallow.
func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) error {
	_, err := q.db.ExecContext(ctx, linkIdentity, arg.Provider, arg.ProviderUserID, arg.UserID)
	return err
}
