// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_events.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrderEvent = `-- name: CreateOrderEvent :exec
INSERT INTO order_events (id, order_id, actor_id, from_status, to_status, note)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrderEventParams struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	ActorID    uuid.NullUUID
	FromStatus sql.NullString
	ToStatus   string
	Note       sql.NullString
}

func (q *Queries) CreateOrderEvent(ctx context.Context, arg CreateOrderEventParams) error {
	_, err := q.db.ExecContext(ctx, createOrderEvent,
		arg.ID,
		arg.OrderID,
		arg.ActorID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	return err
}

const listOrderEvents = `-- name: ListOrderEvents :many
SELECT id, order_id, actor_id, from_status, to_status, note, created_at
FROM order_events
WHERE order_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListOrderEvents(ctx context.Context, orderID uuid.UUID) ([]OrderEvent, error) {
	rows, err := q.db.QueryContext(ctx, listOrderEvents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderEvent
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ActorID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
