// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countActiveOrdersForListing = `-- name: CountActiveOrdersForListing :one
SELECT COUNT(*) FROM orders
WHERE listing_id = $1 AND status IN ('pending', 'confirmed')
`

// pending and confirmed are in flight; completed, cancelled and refunded are
// over and no longer stand in the way of deleting the listing.
func (q *Queries) CountActiveOrdersForListing(ctx context.Context, listingID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveOrdersForListing, listingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersForAdmin = `-- name: CountOrdersForAdmin :one
SELECT COUNT(*) FROM admin_orders
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
  AND ($4::boolean IS NULL OR stuck = $4::boolean)
`

type CountOrdersForAdminParams struct {
	Status      sql.NullString
	CreatedFrom sql.NullTime
	CreatedTo   sql.NullTime
	Stuck       sql.NullBool
}

func (q *Queries) CountOrdersForAdmin(ctx context.Context, arg CountOrdersForAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersForAdmin,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Stuck,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, listing_title)
VALUES ($1, $2, $3, $4, $5, $6, $6::numeric * $5::integer, $7)
RETURNING id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title
`

type CreateOrderParams struct {
	ID           uuid.UUID
	ListingID    uuid.NullUUID
	BuyerID      uuid.UUID
	SellerID     uuid.UUID
	Quantity     int32
	UnitPrice    string
	ListingTitle string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.ID,
		arg.ListingID,
		arg.BuyerID,
		arg.SellerID,
		arg.Quantity,
		arg.UnitPrice,
		arg.ListingTitle,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title FROM orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}

const getOrderResolvability = `-- name: GetOrderResolvability :one
SELECT stuck, stranded FROM admin_orders WHERE id = $1
`

type GetOrderResolvabilityRow struct {
	Stuck    bool
	Stranded bool
}

func (q *Queries) GetOrderResolvability(ctx context.Context, id uuid.UUID) (GetOrderResolvabilityRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderResolvability, id)
	var i GetOrderResolvabilityRow
	err := row.Scan(&i.Stuck, &i.Stranded)
	return i, err
}

const listOrdersForAdmin = `-- name: ListOrdersForAdmin :many
SELECT id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title, handshake_stuck, stranded, stuck FROM admin_orders
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at < $3::timestamptz)
  AND ($4::boolean IS NULL OR stuck = $4::boolean)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListOrdersForAdminParams struct {
	Status      sql.NullString
	CreatedFrom sql.NullTime
	CreatedTo   sql.NullTime
	Stuck       sql.NullBool
	PageOffset  int32
	PageLimit   int32
}

func (q *Queries) ListOrdersForAdmin(ctx context.Context, arg ListOrdersForAdminParams) ([]AdminOrder, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersForAdmin,
		arg.Status,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Stuck,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOrder
	for rows.Next() {
		var i AdminOrder
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerHandedOverAt,
			&i.BuyerReceivedAt,
			&i.ListingTitle,
			&i.HandshakeStuck,
			&i.Stranded,
			&i.Stuck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForUser = `-- name: ListOrdersForUser :many
SELECT id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title FROM orders
WHERE buyer_id = $1 OR seller_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersForUser(ctx context.Context, buyerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersForUser, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerHandedOverAt,
			&i.BuyerReceivedAt,
			&i.ListingTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersToCancelOnDeparture = `-- name: ListOrdersToCancelOnDeparture :many
SELECT id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title FROM orders
WHERE (buyer_id = $1 OR seller_id = $1)
  AND status IN ('pending', 'confirmed')
FOR UPDATE
`

// Every order this account still has in flight, either side.
//
// Deleting an account now ends its sales, so admin_orders.stranded - which
// needs BOTH parties gone with the order still open - can no longer be reached
// by anybody leaving. It still describes rows that predate this change; nothing
// new arrives there.
func (q *Queries) ListOrdersToCancelOnDeparture(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersToCancelOnDeparture, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.BuyerID,
			&i.SellerID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerHandedOverAt,
			&i.BuyerReceivedAt,
			&i.ListingTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderHandedOver = `-- name: MarkOrderHandedOver :one
UPDATE orders
SET seller_handed_over_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title
`

func (q *Queries) MarkOrderHandedOver(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, markOrderHandedOver, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}

const markOrderReceived = `-- name: MarkOrderReceived :one
UPDATE orders
SET buyer_received_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title
`

func (q *Queries) MarkOrderReceived(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, markOrderReceived, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, listing_id, buyer_id, seller_id, quantity, unit_price, total_price, status, created_at, updated_at, seller_handed_over_at, buyer_received_at, listing_title
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.BuyerID,
		&i.SellerID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SellerHandedOverAt,
		&i.BuyerReceivedAt,
		&i.ListingTitle,
	)
	return i, err
}
