// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createResetToken = `-- name: CreateResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateResetTokenParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteDeadResetTokensForUser = `-- name: DeleteDeadResetTokensForUser :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1
    AND (expires_at < now() OR used_at IS NOT NULL)
`

// Tokens that can never be redeemed again: expired, or already spent. Runs on
// the user's own rows as they ask for a new link, so growth is bounded by live
// requests rather than by lifetime resets - no scheduler, and the user_id
// index already covers it. Mirrors DeleteDeadSessionsForUser.
//
// Must run AFTER the cooldown check: LastResetRequestAt reads the newest row
// whether or not it is spent, so deleting first would let anyone bypass the
// cooldown by spending or expiring their link.
func (q *Queries) DeleteDeadResetTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeadResetTokensForUser, userID)
	return err
}

const findLiveResetToken = `-- name: FindLiveResetToken :one
SELECT token_hash, user_id, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > now()
`

func (q *Queries) FindLiveResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, findLiveResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateResetTokensForUser = `-- name: InvalidateResetTokensForUser :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1
    AND used_at IS NULL
`

func (q *Queries) InvalidateResetTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, invalidateResetTokensForUser, userID)
	return err
}

const lastResetRequestAt = `-- name: LastResetRequestAt :one
SELECT created_at FROM password_reset_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LastResetRequestAt(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, lastResetRequestAt, userID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const markResetTokenUsed = `-- name: MarkResetTokenUsed :execrows
UPDATE password_reset_tokens
SET used_at = now()
WHERE token_hash = $1
    AND used_at IS NULL
`

func (q *Queries) MarkResetTokenUsed(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResetTokenUsed, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
