// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearAvatar = `-- name: ClearAvatar :one
WITH previous AS (
    SELECT avatar_filename FROM profiles WHERE id = $1 FOR UPDATE
)
UPDATE profiles
SET avatar_filename = NULL
FROM previous
WHERE profiles.id = $1
RETURNING previous.avatar_filename
`

// Locked for the same reason as SetAvatar: a DELETE racing a POST orphans a
// file in exactly the same way.
func (q *Queries) ClearAvatar(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, clearAvatar, id)
	var avatar_filename sql.NullString
	err := row.Scan(&avatar_filename)
	return avatar_filename, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, firstname, lastname, bio, phone_number, date_of_birth)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, firstname, lastname, bio, phone_number, date_of_birth, avatar_filename
`

type CreateProfileParams struct {
	ID          uuid.UUID
	Firstname   sql.NullString
	Lastname    sql.NullString
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Bio,
		arg.PhoneNumber,
		arg.DateOfBirth,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.AvatarFilename,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const ensureProfile = `-- name: EnsureProfile :exec
INSERT INTO profiles (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ensureProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, firstname, lastname, bio, phone_number, date_of_birth, avatar_filename FROM profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.AvatarFilename,
	)
	return i, err
}

const getProfileForUpdate = `-- name: GetProfileForUpdate :one
SELECT id, firstname, lastname, bio, phone_number, date_of_birth, avatar_filename FROM profiles
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetProfileForUpdate(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileForUpdate, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.AvatarFilename,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, firstname, lastname, bio, phone_number, date_of_birth, avatar_filename FROM profiles
ORDER BY id
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Bio,
			&i.PhoneNumber,
			&i.DateOfBirth,
			&i.AvatarFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scrubProfile = `-- name: ScrubProfile :one
WITH previous AS (
    SELECT avatar_filename FROM profiles WHERE id = $1 FOR UPDATE
)
UPDATE profiles
SET firstname       = NULL,
    lastname        = NULL,
    bio             = NULL,
    phone_number    = NULL,
    date_of_birth   = NULL,
    avatar_filename = NULL
FROM previous
WHERE profiles.id = $1
RETURNING previous.avatar_filename
`

// Same CTE-with-FOR-UPDATE shape as ClearAvatar, and for the same two reasons:
// the lock stops an avatar upload racing the scrub and orphaning a file, and
// the CTE reads the pre-update filename - a plain RETURNING avatar_filename
// would hand back the NULL we just wrote, leaving the file on disk forever.
func (q *Queries) ScrubProfile(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, scrubProfile, id)
	var avatar_filename sql.NullString
	err := row.Scan(&avatar_filename)
	return avatar_filename, err
}

const setAvatar = `-- name: SetAvatar :one
WITH previous AS (
    SELECT avatar_filename FROM profiles WHERE id = $1 FOR UPDATE
)
UPDATE profiles
SET avatar_filename = $2
FROM previous
WHERE profiles.id = $1
RETURNING previous.avatar_filename
`

type SetAvatarParams struct {
	ID             uuid.UUID
	AvatarFilename sql.NullString
}

// FOR UPDATE is load-bearing. Without it the CTE reads the statement snapshot
// while the UPDATE re-reads the row after the lock is released, so two
// overlapping uploads both report the same previous filename - and the one
// neither of them named is never deleted.
func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, setAvatar, arg.ID, arg.AvatarFilename)
	var avatar_filename sql.NullString
	err := row.Scan(&avatar_filename)
	return avatar_filename, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET firstname     = $2,
    lastname      = $3,
    bio           = $4,
    phone_number  = $5,
    date_of_birth = $6
WHERE id = $1
RETURNING id, firstname, lastname, bio, phone_number, date_of_birth, avatar_filename
`

type UpdateProfileParams struct {
	ID          uuid.UUID
	Firstname   sql.NullString
	Lastname    sql.NullString
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Bio,
		arg.PhoneNumber,
		arg.DateOfBirth,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.AvatarFilename,
	)
	return i, err
}
