// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (id, firstname, lastname, bio, phone_number, date_of_birth)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, firstname, lastname, bio, phone_number, date_of_birth
`

type CreateProfileParams struct {
	ID          uuid.UUID
	Firstname   string
	Lastname    string
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Bio,
		arg.PhoneNumber,
		arg.DateOfBirth,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT id, firstname, lastname, bio, phone_number, date_of_birth FROM profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Bio,
		&i.PhoneNumber,
		&i.DateOfBirth,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, firstname, lastname, bio, phone_number, date_of_birth FROM profiles
ORDER BY id
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Bio,
			&i.PhoneNumber,
			&i.DateOfBirth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET firstname     = $2,
    lastname      = $3,
    bio           = $4,
    phone_number  = $5,
    date_of_birth = $6
WHERE id = $1
`

type UpdateProfileParams struct {
	ID          uuid.UUID
	Firstname   string
	Lastname    string
	Bio         sql.NullString
	PhoneNumber sql.NullString
	DateOfBirth sql.NullTime
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Bio,
		arg.PhoneNumber,
		arg.DateOfBirth,
	)
	return err
}
