// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countReviewsForSeller = `-- name: CountReviewsForSeller :one
SELECT COUNT(*) FROM reviews WHERE seller_id = $1
`

func (q *Queries) CountReviewsForSeller(ctx context.Context, sellerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsForSeller, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, order_id, seller_id, reviewer_id, rating, comment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, seller_id, reviewer_id, rating, comment, created_at, updated_at
`

type CreateReviewParams struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	SellerID   uuid.UUID
	ReviewerID uuid.NullUUID
	Rating     int32
	Comment    sql.NullString
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.ID,
		arg.OrderID,
		arg.SellerID,
		arg.ReviewerID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const detachReviewer = `-- name: DetachReviewer :exec
UPDATE reviews SET reviewer_id = NULL WHERE reviewer_id = $1::uuid
`

// The FK is ON DELETE SET NULL, but account deletion anonymises rather than
// deleting, so nothing fires it.
func (q *Queries) DetachReviewer(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, detachReviewer, userID)
	return err
}

const getReviewForOrder = `-- name: GetReviewForOrder :one
SELECT id, order_id, seller_id, reviewer_id, rating, comment, created_at, updated_at FROM reviews
WHERE order_id = $1
`

func (q *Queries) GetReviewForOrder(ctx context.Context, orderID uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewForOrder, orderID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsAboutUserForExport = `-- name: ListReviewsAboutUserForExport :many
SELECT id, order_id, seller_id, reviewer_id, rating, comment, created_at, updated_at FROM reviews
WHERE seller_id = $1
ORDER BY created_at
`

// Unpaginated, for the same reason as the notifications twin: the public
// profile pages through these, an export must not.
func (q *Queries) ListReviewsAboutUserForExport(ctx context.Context, sellerID uuid.UUID) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsAboutUserForExport, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ReviewerID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForSeller = `-- name: ListReviewsForSeller :many
SELECT
    r.id, r.order_id, r.rating, r.comment, r.created_at, r.updated_at,
    r.reviewer_id,
    u.username   AS reviewer_username,
    u.deleted_at AS reviewer_deleted_at
FROM reviews r
LEFT JOIN users u ON u.id = r.reviewer_id
WHERE r.seller_id = $1
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ListReviewsForSellerParams struct {
	SellerID   uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListReviewsForSellerRow struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	Rating            int32
	Comment           sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ReviewerID        uuid.NullUUID
	ReviewerUsername  sql.NullString
	ReviewerDeletedAt sql.NullTime
}

// LEFT JOIN, not JOIN: reviewer_id is NULL once that account is deleted, and
// an inner join would drop exactly the reviews the SET NULL preserves.
func (q *Queries) ListReviewsForSeller(ctx context.Context, arg ListReviewsForSellerParams) ([]ListReviewsForSellerRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsForSeller, arg.SellerID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForSellerRow
	for rows.Next() {
		var i ListReviewsForSellerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerID,
			&i.ReviewerUsername,
			&i.ReviewerDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsWrittenBy = `-- name: ListReviewsWrittenBy :many
SELECT id, order_id, seller_id, reviewer_id, rating, comment, created_at, updated_at FROM reviews
WHERE reviewer_id = $1
ORDER BY created_at
`

// The other direction from ListReviewsForSeller: what this account said about
// other people, which is theirs to take with them.
func (q *Queries) ListReviewsWrittenBy(ctx context.Context, reviewerID uuid.NullUUID) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsWrittenBy, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.ReviewerID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerRating = `-- name: SellerRating :one
SELECT
    COALESCE(AVG(rating), 0)::float8 AS average,
    COUNT(*)                         AS total
FROM reviews
WHERE seller_id = $1
`

type SellerRatingRow struct {
	Average float64
	Total   int64
}

// AVG returns numeric, which sqlc types as a string; ::float8 makes it a
// float64. COALESCE covers a seller with no reviews, where AVG is NULL.
func (q *Queries) SellerRating(ctx context.Context, sellerID uuid.UUID) (SellerRatingRow, error) {
	row := q.db.QueryRowContext(ctx, sellerRating, sellerID)
	var i SellerRatingRow
	err := row.Scan(&i.Average, &i.Total)
	return i, err
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating     = $1,
    comment    = CASE WHEN $2::boolean
                      THEN $3
                      ELSE comment END,
    updated_at = now()
WHERE id = $4 AND reviewer_id = $5::uuid
RETURNING id, order_id, seller_id, reviewer_id, rating, comment, created_at, updated_at
`

type UpdateReviewParams struct {
	Rating     int32
	CommentSet bool
	Comment    sql.NullString
	ID         uuid.UUID
	ReviewerID uuid.UUID
}

// Scoped to the author, so "not yours" and "does not exist" are the same
// no-rows answer.
// comment_set carries the difference between "absent" and "explicitly
// cleared": absent leaves the column alone, so a rating fix cannot silently
// destroy text the author never touched.
func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, updateReview,
		arg.Rating,
		arg.CommentSet,
		arg.Comment,
		arg.ID,
		arg.ReviewerID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.ReviewerID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
