// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_listings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const listSaveListings = `-- name: ListSaveListings :many
SELECT l.id, l.seller_id, l.title, l.description, l.category, l.price, l.quantity, l.unit, l.created_at, l.updated_at FROM saved_listings s
JOIN listings l ON l.id = s.listing_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

// Joins the link table back to listings and selects l.* so sqlc reuses the
// existing Listing struct - no new type, and dtos.ToListingResponses still
// applies. Order by when it was SAVED (s.created_at), not when the listing
// was posted (l.created_at) - that's what makes it read like a wishlist.
func (q *Queries) ListSaveListings(ctx context.Context, userID uuid.UUID) ([]Listing, error) {
	rows, err := q.db.QueryContext(ctx, listSaveListings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveListing = `-- name: SaveListing :exec
INSERT INTO saved_listings (user_id, listing_id)
VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
`

type SaveListingParams struct {
	UserID    uuid.UUID
	ListingID int32
}

// ON CONFLICT DO NOTHING makes this idempotent: saving the same listing twice
// is a no-op instead of a unique-violation error. The (user_id, listing_id)
// named in the conflict clause is the composite PK from migration 009.
func (q *Queries) SaveListing(ctx context.Context, arg SaveListingParams) error {
	_, err := q.db.ExecContext(ctx, saveListing, arg.UserID, arg.ListingID)
	return err
}

const unsaveListing = `-- name: UnsaveListing :execrows
DELETE FROM saved_listings
WHERE user_id = $1 AND listing_id = $2
`

type UnsaveListingParams struct {
	UserID    uuid.UUID
	ListingID int32
}

// :execrows (not :exec) so Go gets the rows-aaffected count back and can tell
// "removed it" (1) from "there was nothing removed" (0) -> honest 404.
func (q *Queries) UnsaveListing(ctx context.Context, arg UnsaveListingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unsaveListing, arg.UserID, arg.ListingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
