// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_listings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSavedForUser = `-- name: DeleteSavedForUser :exec
DELETE FROM saved_listings WHERE user_id = $1
`

func (q *Queries) DeleteSavedForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSavedForUser, userID)
	return err
}

const listSavedListings = `-- name: ListSavedListings :many
SELECT l.id, l.seller_id, l.title, l.description, l.category, l.price, l.quantity, l.unit, l.created_at, l.updated_at, l.removed_at FROM saved_listings s
JOIN listings l ON l.id = s.listing_id
WHERE s.user_id = $1 AND l.removed_at IS NULL
  AND EXISTS (SELECT 1 FROM users u WHERE u.id = l.seller_id AND u.is_visible)
  -- A block hides the seller entirely, so a listing saved before it must go
  -- with them: otherwise the row is here to click and only the order refuses.
  -- The save itself is kept, so unblocking brings it back.
  AND NOT EXISTS (
      SELECT 1 FROM blocks b
      WHERE (b.blocker_id = $1 AND b.blocked_id = l.seller_id)
         OR (b.blocker_id = l.seller_id AND b.blocked_id = $1)
  )
ORDER BY s.created_at DESC
`

func (q *Queries) ListSavedListings(ctx context.Context, userID uuid.UUID) ([]Listing, error) {
	rows, err := q.db.QueryContext(ctx, listSavedListings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Quantity,
			&i.Unit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaversOfListing = `-- name: ListSaversOfListing :many
SELECT user_id FROM saved_listings
WHERE listing_id = $1
  AND user_id <> $2
`

type ListSaversOfListingParams struct {
	ListingID  uuid.UUID
	ExceptUser uuid.UUID
}

func (q *Queries) ListSaversOfListing(ctx context.Context, arg ListSaversOfListingParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listSaversOfListing, arg.ListingID, arg.ExceptUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveListing = `-- name: SaveListing :exec
INSERT INTO saved_listings (user_id, listing_id)
VALUES ($1, $2)
ON CONFLICT (user_id, listing_id) DO NOTHING
`

type SaveListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) SaveListing(ctx context.Context, arg SaveListingParams) error {
	_, err := q.db.ExecContext(ctx, saveListing, arg.UserID, arg.ListingID)
	return err
}

const unsaveListing = `-- name: UnsaveListing :execrows
DELETE FROM saved_listings
WHERE user_id = $1 AND listing_id = $2
`

type UnsaveListingParams struct {
	UserID    uuid.UUID
	ListingID uuid.UUID
}

func (q *Queries) UnsaveListing(ctx context.Context, arg UnsaveListingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unsaveListing, arg.UserID, arg.ListingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
