// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteDeadSessionsForUser = `-- name: DeleteDeadSessionsForUser :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
    AND (
        expires_at < now()
        OR (revoked_at IS NOT NULL AND revoked_at < $2)
      )
`

type DeleteDeadSessionsForUserParams struct {
	UserID        uuid.UUID
	RevokedBefore sql.NullTime
}

// Sessions that can never be redeemed again: expired, or revoked long enough
// ago that the grace window has closed. Runs on the user's own rows as they
// issue a new session, so growth is bounded by active sessions rather than by
// lifetime logins - no scheduler, and the user_id index already covers it.
func (q *Queries) DeleteDeadSessionsForUser(ctx context.Context, arg DeleteDeadSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeadSessionsForUser, arg.UserID, arg.RevokedBefore)
	return err
}

const findLiveSession = `-- name: FindLiveSession :one
SELECT token_hash, user_id, expires_at, revoked_at, revoked_reason, created_at FROM refresh_tokens
WHERE token_hash = $1
    AND expires_at > now()
    AND (
        revoked_at IS NULL
        OR (revoked_reason = 'rotated' AND revoked_at > $2)
      )
`

type FindLiveSessionParams struct {
	TokenHash    string
	RevokedAfter sql.NullTime
}

func (q *Queries) FindLiveSession(ctx context.Context, arg FindLiveSessionParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findLiveSession, arg.TokenHash, arg.RevokedAfter)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionByHash = `-- name: FindSessionByHash :one
SELECT token_hash, user_id, expires_at, revoked_at, revoked_reason, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) FindSessionByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findSessionByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE refresh_tokens
SET revoked_at = now(),
    revoked_reason = $1
WHERE token_hash = $2
    AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Reason    sql.NullString
	TokenHash string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, arg.Reason, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSessionsForPasswordReset = `-- name: RevokeSessionsForPasswordReset :exec
UPDATE refresh_tokens
SET revoked_at = now(),
    revoked_reason = 'password_reset'
WHERE user_id = $1
    AND expires_at > now()
    AND (revoked_at IS NULL OR revoked_reason = 'rotated')
`

// A copy of RevokeSessionsForUser with a different reason rather than a
// parameter on it: parameterising would change the signature every logout call
// site uses, to save five lines.
func (q *Queries) RevokeSessionsForPasswordReset(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForPasswordReset, userID)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE refresh_tokens
SET revoked_at = now(),
    revoked_reason = 'logout'
WHERE user_id = $1
    AND expires_at > now()
    AND (revoked_at IS NULL OR revoked_reason = 'rotated')
`

// Rotated rows are included, not just live ones: FindLiveSession still accepts
// a rotated token for the length of the grace window, so skipping them would
// leave a logged-out user redeemable for another 30 seconds.
func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForUser, userID)
	return err
}

const storeSession = `-- name: StoreSession :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type StoreSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreSession(ctx context.Context, arg StoreSessionParams) error {
	_, err := q.db.ExecContext(ctx, storeSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}
