// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findLiveSession = `-- name: FindLiveSession :one
SELECT token_hash, user_id, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1
    AND expires_at > now()
    AND (revoked_at IS NULL OR revoked_at > $2)
`

type FindLiveSessionParams struct {
	TokenHash    string
	RevokedAfter sql.NullTime
}

func (q *Queries) FindLiveSession(ctx context.Context, arg FindLiveSessionParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findLiveSession, arg.TokenHash, arg.RevokedAfter)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForUser, userID)
	return err
}

const storeSession = `-- name: StoreSession :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type StoreSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreSession(ctx context.Context, arg StoreSessionParams) error {
	_, err := q.db.ExecContext(ctx, storeSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}
