// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const attachTag = `-- name: AttachTag :exec
INSERT INTO listing_tags (listing_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (listing_id, tag_id) DO NOTHING
`

type AttachTagParams struct {
	ListingID uuid.UUID
	TagID     int32
}

func (q *Queries) AttachTag(ctx context.Context, arg AttachTagParams) error {
	_, err := q.db.ExecContext(ctx, attachTag, arg.ListingID, arg.TagID)
	return err
}

const deleteUnusedTags = `-- name: DeleteUnusedTags :execrows
DELETE FROM tags t
WHERE NOT EXISTS (SELECT 1 FROM listing_tags lt WHERE lt.tag_id = t.id)
`

func (q *Queries) DeleteUnusedTags(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedTags)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const detachAllTags = `-- name: DetachAllTags :exec
DELETE FROM listing_tags
WHERE listing_id = $1
`

func (q *Queries) DetachAllTags(ctx context.Context, listingID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, detachAllTags, listingID)
	return err
}

const listTagsForListing = `-- name: ListTagsForListing :many
SELECT t.name FROM listing_tags lt
JOIN tags t ON t.id = lt.tag_id
WHERE lt.listing_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsForListing(ctx context.Context, listingID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForListings = `-- name: ListTagsForListings :many
SELECT lt.listing_id, t.name FROM listing_tags lt
JOIN tags t ON t.id = lt.tag_id
WHERE lt.listing_id = ANY($1::uuid[])
ORDER BY lt.listing_id, t.name
`

type ListTagsForListingsRow struct {
	ListingID uuid.UUID
	Name      string
}

func (q *Queries) ListTagsForListings(ctx context.Context, listingIds []uuid.UUID) ([]ListTagsForListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForListings, pq.Array(listingIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForListingsRow
	for rows.Next() {
		var i ListTagsForListingsRow
		if err := rows.Scan(&i.ListingID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTagsForSweep = `-- name: LockTagsForSweep :exec
SELECT pg_advisory_xact_lock(5170163)
`

func (q *Queries) LockTagsForSweep(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockTagsForSweep)
	return err
}

const lockTagsShared = `-- name: LockTagsShared :exec
SELECT pg_advisory_xact_lock_shared(5170163)
`

func (q *Queries) LockTagsShared(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockTagsShared)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
