// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_actions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserAction = `-- name: CreateUserAction :one
INSERT INTO user_actions (id, subject_id, moderator_id, action, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subject_id, moderator_id, action, note, created_at
`

type CreateUserActionParams struct {
	ID          uuid.UUID
	SubjectID   uuid.UUID
	ModeratorID uuid.NullUUID
	Action      string
	Note        sql.NullString
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) (UserAction, error) {
	row := q.db.QueryRowContext(ctx, createUserAction,
		arg.ID,
		arg.SubjectID,
		arg.ModeratorID,
		arg.Action,
		arg.Note,
	)
	var i UserAction
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ModeratorID,
		&i.Action,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const detachUserActionModerator = `-- name: DetachUserActionModerator :exec
UPDATE user_actions SET moderator_id = NULL WHERE moderator_id = $1::uuid
`

// ON DELETE SET NULL never fires because account deletion anonymises rather
// than deleting, so detaching has to be explicit.
func (q *Queries) DetachUserActionModerator(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, detachUserActionModerator, userID)
	return err
}

const listUserActions = `-- name: ListUserActions :many
SELECT id, subject_id, moderator_id, action, note, created_at FROM user_actions
WHERE subject_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserActions(ctx context.Context, subjectID uuid.UUID) ([]UserAction, error) {
	rows, err := q.db.QueryContext(ctx, listUserActions, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAction
	for rows.Next() {
		var i UserAction
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ModeratorID,
			&i.Action,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
