// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password)
VALUES (
	$1, $2, $3, $4
)
RETURNING id, email, username, password, role, created_at, updated_at, last_seen_at, show_online_status
`

type CreateUserParams struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ShowOnlineStatus,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const emailOrUsernameTaken = `-- name: EmailOrUsernameTaken :one
SELECT
    EXISTS(SELECT 1 FROM users u WHERE lower(u.email) = lower($1))       AS email_taken,
    EXISTS(SELECT 1 FROM users u WHERE lower(u.username) = lower($2)) AS username_taken
`

type EmailOrUsernameTakenParams struct {
	Email    string
	Username string
}

type EmailOrUsernameTakenRow struct {
	EmailTaken    bool
	UsernameTaken bool
}

func (q *Queries) EmailOrUsernameTaken(ctx context.Context, arg EmailOrUsernameTakenParams) (EmailOrUsernameTakenRow, error) {
	row := q.db.QueryRowContext(ctx, emailOrUsernameTaken, arg.Email, arg.Username)
	var i EmailOrUsernameTakenRow
	err := row.Scan(&i.EmailTaken, &i.UsernameTaken)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password, role, created_at, updated_at, last_seen_at, show_online_status FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ShowOnlineStatus,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, role, created_at, updated_at, last_seen_at, show_online_status FROM users
WHERE lower(email) = lower($1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ShowOnlineStatus,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users
WHERE id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password, role, created_at, updated_at, last_seen_at, show_online_status FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.ShowOnlineStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE users
SET last_seen_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) TouchLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchLastSeen, id)
	return err
}

const updateShowOnlineStatus = `-- name: UpdateShowOnlineStatus :one
UPDATE users
SET show_online_status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, email, username, password, role, created_at, updated_at, last_seen_at, show_online_status
`

type UpdateShowOnlineStatusParams struct {
	ID               uuid.UUID
	ShowOnlineStatus bool
}

func (q *Queries) UpdateShowOnlineStatus(ctx context.Context, arg UpdateShowOnlineStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateShowOnlineStatus, arg.ID, arg.ShowOnlineStatus)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ShowOnlineStatus,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2,
	email = $3,
	updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Username string
	Email    string
}

// No callers today. Whoever wires "edit profile" must normalise first the way
// normalizeSignupInput does, or padded and case-variant names get back in
// through this door.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.ID, arg.Username, arg.Email)
	return err
}
