-- +goose Up
--
-- One baseline replacing migrations 001-021, which had grown to twenty-one
-- files of which eleven were corrections. The old files remain in git history.
-- This describes the schema as it is, with two sweeps applied:
--
-- 1. Ids are uuid everywhere, replacing the uuid-for-people / serial-for-content
--    split. Specifically uuid v7, generated by the application with
--    uuid.NewV7(): the timestamp lives in the high bits, so ORDER BY id is
--    still chronological and the message cursor (id > $2) still works. Random
--    v4 would have made chat message order arbitrary and broken pagination.
--
--    There is deliberately no DEFAULT on any id, so a v4 can never appear by
--    accident. Note what that does and does not catch: raw SQL omitting the
--    column fails immediately on NOT NULL, but a Go struct with the field
--    unset sends uuid.Nil, which inserts silently and only collides on the
--    second row. uuid.Nil also sorts below every v7, so a forgotten message id
--    would jump to the top of its thread.
--    Postgres 16 has no uuidv7(), and a SQL implementation would only order to
--    the millisecond; order_events writes two rows in one transaction that
--    share a created_at and need the id tiebreak.
--
-- 2. Every timestamp is timestamptz. Plain `timestamp` discards the offset on
--    write, so a value written at +03:00 compares wrongly against now() in UTC.
--    That is what let an expired refresh token read as live, and it is the kind
--    of bug that passes in CI and fails on a developer's machine.
--
-- Nothing else changed. Column names, order, lengths, nullability, constraint
-- names, foreign key actions and indexes are carried across verbatim.
-- Constraint names are load-bearing: the service maps several of them to a 404
-- or a 409, so a rename becomes a 500.

CREATE TABLE users (
    id                 uuid PRIMARY KEY,
    email              varchar(150) NOT NULL,
    username           varchar(150) NOT NULL,
    password           varchar(255) NOT NULL,
    role               varchar(20) NOT NULL DEFAULT 'USER',
    created_at         timestamptz DEFAULT now(),
    updated_at         timestamptz DEFAULT now(),
    last_seen_at       timestamptz,
    show_online_status boolean NOT NULL DEFAULT true,

    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- Functional, not plain UNIQUE: uniqueness ignores case, so Forager and forager
-- are one account. The lookups compare lower(...) = lower(...) so they use
-- these rather than falling back to a sequential scan.
CREATE UNIQUE INDEX users_email_lower_uq    ON users (lower(email));
CREATE UNIQUE INDEX users_username_lower_uq ON users (lower(username));

CREATE TABLE profiles (
    id            uuid PRIMARY KEY,
    firstname     varchar(150),
    lastname      varchar(150),
    bio           text,
    phone_number  varchar(15),
    -- A birthday has no timezone, so this stays a date.
    date_of_birth date,

    CONSTRAINT profiles_users_fk FOREIGN KEY (id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE listings (
    id          uuid PRIMARY KEY,
    seller_id   uuid NOT NULL,
    title       varchar(100) NOT NULL,
    description text,
    category    varchar(50) NOT NULL,
    price       numeric(10,2) NOT NULL,
    quantity    integer NOT NULL,
    unit        varchar(20) NOT NULL,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),

    CONSTRAINT listings_price_check CHECK (price > 0),
    -- Zero is sold out, not invalid.
    CONSTRAINT listings_quantity_check CHECK (quantity >= 0),

    CONSTRAINT listings_seller_id_fkey FOREIGN KEY (seller_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_listings_seller_id ON listings (seller_id);

CREATE TABLE addresses (
    id         uuid PRIMARY KEY,
    user_id    uuid NOT NULL,
    location   varchar(100),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),

    CONSTRAINT addresses_user_id_key UNIQUE (user_id),
    CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id                    uuid PRIMARY KEY,
    listing_id            uuid NOT NULL,
    buyer_id              uuid NOT NULL,
    seller_id             uuid NOT NULL,
    quantity              integer NOT NULL,
    unit_price            numeric(10,2) NOT NULL,
    total_price           numeric(10,2) NOT NULL,
    status                text NOT NULL DEFAULT 'pending',
    created_at            timestamptz DEFAULT now(),
    updated_at            timestamptz DEFAULT now(),
    seller_handed_over_at timestamptz,
    buyer_received_at     timestamptz,
    -- Snapshotted at purchase, so an order still reads correctly after the
    -- listing is edited.
    listing_title         text NOT NULL,

    CONSTRAINT orders_quantity_check    CHECK (quantity > 0),
    CONSTRAINT orders_unit_price_check  CHECK (unit_price > 0),
    CONSTRAINT orders_total_price_check CHECK (total_price > 0),
    CONSTRAINT orders_status_check
        CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),

    -- RESTRICT, not CASCADE: an order is a record of what happened, so neither
    -- party nor the listing can be deleted out from under it. A history either
    -- side can erase is not evidence.
    CONSTRAINT orders_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE RESTRICT,
    CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id)
        REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT orders_seller_id_fkey FOREIGN KEY (seller_id)
        REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX idx_orders_buyer_id   ON orders (buyer_id);
CREATE INDEX idx_orders_seller_id  ON orders (seller_id);
CREATE INDEX idx_orders_listing_id ON orders (listing_id);

CREATE TABLE saved_listings (
    user_id    uuid NOT NULL,
    listing_id uuid NOT NULL,
    created_at timestamptz DEFAULT now(),

    PRIMARY KEY (user_id, listing_id),

    CONSTRAINT saved_listings_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT saved_listings_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE CASCADE
);

CREATE INDEX idx_saved_listings_listing_id ON saved_listings (listing_id);

CREATE TABLE listing_images (
    id         uuid PRIMARY KEY,
    listing_id uuid NOT NULL,
    filename   text NOT NULL,
    position   integer NOT NULL DEFAULT 0,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT listing_images_filename_key UNIQUE (filename),
    -- DEFERRABLE: reordering swaps two positions inside one transaction, which
    -- is momentarily a duplicate. Checked at commit rather than per statement.
    CONSTRAINT listing_images_listing_position_uq UNIQUE (listing_id, position)
        DEFERRABLE INITIALLY DEFERRED,

    CONSTRAINT listing_images_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE CASCADE
);

CREATE INDEX idx_listing_images_listing_id ON listing_images (listing_id);

CREATE TABLE conversations (
    id            uuid PRIMARY KEY,
    -- Nullable, with SET NULL below: a thread outlives the listing it started
    -- from, so the title is snapshotted the way an order's is.
    listing_id    uuid,
    listing_title text NOT NULL,
    buyer_id      uuid NOT NULL,
    seller_id     uuid NOT NULL,
    status        text NOT NULL DEFAULT 'pending',
    created_at    timestamptz DEFAULT now(),
    updated_at    timestamptz DEFAULT now(),

    CONSTRAINT conversations_status_check
        CHECK (status IN ('pending', 'accepted', 'declined')),
    CONSTRAINT conversations_no_self_chat CHECK (buyer_id <> seller_id),
    -- One thread per buyer per listing.
    CONSTRAINT conversations_listing_buyer_uq UNIQUE (listing_id, buyer_id),

    CONSTRAINT conversations_listing_id_fkey FOREIGN KEY (listing_id)
        REFERENCES listings(id) ON DELETE SET NULL,
    CONSTRAINT conversations_buyer_id_fkey FOREIGN KEY (buyer_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT conversations_seller_id_fkey FOREIGN KEY (seller_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_conversations_buyer_id  ON conversations (buyer_id);
CREATE INDEX idx_conversations_seller_id ON conversations (seller_id);

CREATE TABLE messages (
    id              uuid PRIMARY KEY,
    conversation_id uuid NOT NULL,
    sender_id       uuid NOT NULL,
    body            text NOT NULL,
    read_at         timestamptz,
    created_at      timestamptz DEFAULT now(),

    CONSTRAINT messages_body_check CHECK (length(btrim(body)) > 0),

    CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id)
        REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- Serves both the thread listing and the "messages after this one" cursor. It
-- only works because ids are time-ordered - see the note about v7 above.
CREATE INDEX idx_messages_conversation_id ON messages (conversation_id, id);

CREATE TABLE follows (
    follower_id uuid NOT NULL,
    followee_id uuid NOT NULL,
    created_at  timestamptz DEFAULT now(),

    PRIMARY KEY (follower_id, followee_id),

    CONSTRAINT follows_no_self_follow CHECK (follower_id <> followee_id),

    -- Named rather than left to Postgres: the service maps these exact names to
    -- a 404, so an auto-generated name would turn a rewrite into a 500.
    CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT follows_followee_id_fkey FOREIGN KEY (followee_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_follows_followee_id ON follows (followee_id);

CREATE TABLE order_events (
    id          uuid PRIMARY KEY,
    order_id    uuid NOT NULL,
    -- SET NULL, not CASCADE: the event outlives the account that caused it, so
    -- a deleted user leaves the history intact with an anonymous actor.
    actor_id    uuid,
    from_status text,
    to_status   text NOT NULL,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT order_events_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT order_events_actor_id_fkey FOREIGN KEY (actor_id)
        REFERENCES users(id) ON DELETE SET NULL
);

-- Two events can share one transaction's created_at, so id is the tiebreak and
-- has to be ordered. Covers the timeline query's full ORDER BY.
CREATE INDEX idx_order_events_order_id ON order_events (order_id, created_at, id);

CREATE TABLE refresh_tokens (
    token_hash     text PRIMARY KEY,
    user_id        uuid NOT NULL,
    expires_at     timestamptz NOT NULL,
    revoked_at     timestamptz,
    revoked_reason text,
    created_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT refresh_tokens_revoked_reason_check
        CHECK (revoked_reason IN ('rotated', 'logout')),
    CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE api_keys (
    id           uuid PRIMARY KEY,
    user_id      uuid NOT NULL,
    name         text NOT NULL,
    key_hash     text NOT NULL,
    key_prefix   text NOT NULL,
    last_used_at timestamptz,
    revoked_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT api_keys_name_not_blank CHECK (btrim(name) <> ''),
    -- Unique because every authenticated request looks a key up by its hash;
    -- the constraint is also that index.
    CONSTRAINT api_keys_key_hash_uq UNIQUE (key_hash),
    CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_api_keys_user_id ON api_keys (user_id);

-- +goose Down
-- This baseline replaced the chain that built the schema incrementally, so
-- there is no earlier state to return to. Down drops everything.
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS order_events;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS listing_images;
DROP TABLE IF EXISTS saved_listings;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS users;
