package dtos

import (
	"strconv"
	"time"

	"github.com/google/uuid"

	"github.com/IbnBaqqi/transcendence/internal/database"
)

// --- Request DTOs ---

type CreateListingInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Price       float64 `json:"price"`
	Quantity    int32   `json:"quantity"`
	Unit        string  `json:"unit"`
}

type UpdateListingInput struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Price       float64 `json:"price"`
	Quantity    int32   `json:"quantity"`
	Unit        string  `json:"unit"`
}

// --- Search DTOs ---

// ListingSearchQuery holds raw, unparsed values pulled from URL query
// params. Parsing/validation happens in service layer.
type ListingSearchQuery struct {
	Keyword  string
	Category string
	MinPrice string
	MaxPrice string
	Location string
	Page     string
	Limit    string
}

type PaginatedListings struct {
	Items      []ListingResponse `json:"items"`
	Total      int64             `json:"total"`
	Page       int               `json:"page"`
	Limit      int               `json:"limit"`
	TotalPages int               `json:"total_pages"`
}

// --- Response DTOs ---

// ListingResponse is the public JSON shape for a listing.
//
// Why this exists: database.Listing is generated by sqlc, so it carries no
// json tags (keys leak out as Go field names like "Title"), and nullable
// columns arrive as sql.NullString / sql.NullTime, which marshal as
// {"String": "...", "Valid": true}. Adding tags to the generated struct is
// not an option - `make sqlc` overwrites that file. So we map to a type we
// own, and this struct becomes the API's actual contract.
type ListingResponse struct {
	ID          int32     `json:"id"`
	SellerID    uuid.UUID `json:"seller_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	Price       float64   `json:"price"`
	Quantity    int32     `json:"quantity"`
	Unit        string    `json:"unit"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ToListingResponse converts one database row into the public shape.
func ToListingResponse(l database.Listing) ListingResponse {
	// Price is NUMERIC in Postgres, which sqlc maps to string. Reaching a
	// non-numeric value here would take a direct SQL insert - the API always
	// writes this column via strconv.FormatFloat - so 0 is a safe fallback.
	price, _ := strconv.ParseFloat(l.Price, 64)

	return ListingResponse{
		ID:       l.ID,
		SellerID: l.SellerID,
		Title:    l.Title,
		// .String is "" when the column is NULL, which is what we want to
		// send: callers get a plain string instead of a null wrapper.
		Description: l.Description.String,
		Category:    l.Category,
		Price:       price,
		Quantity:    l.Quantity,
		Unit:        l.Unit,
		// .Time is the zero time when the column is NULL, which serialises as
		// "0001-01-01T00:00:00Z". Both columns are DEFAULT CURRENT_TIMESTAMP
		// but not NOT NULL, so only a deliberate NULL insert would hit that.
		CreatedAt: l.CreatedAt.Time,
		UpdatedAt: l.UpdatedAt.Time,
	}
}

// ToListingResponses converts a slice of rows.
//
// make(..., 0, len(rows)) creates an EMPTY slice with room pre-allocated.
// The emptiness matters: a nil slice marshals to JSON `null`, an empty one
// marshals to `[]`. Returning [] means clients can treat the result as a
// list without a null check first.
func ToListingResponses(rows []database.Listing) []ListingResponse {
	out := make([]ListingResponse, 0, len(rows))
	for _, r := range rows {
		out = append(out, ToListingResponse(r))
	}
	return out
}
